// <auto-generated />
namespace EntityExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class str22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(str22));
        
        string IMigrationMetadata.Id
        {
            get { return "201512010919242_str22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
